DROP TABLE IF EXISTS clubs;
DROP TABLE IF EXISTS competitions;

CREATE TABLE clubs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email NVARCHAR(320),
  points INTEGER
);

CREATE TABLE competitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  date TIMESTAMP NOT NULL,
  numberOfPlaces INTEGER
);

CREATE TABLE booking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_competition INTEGER,
  id_club INTEGER,
  nbPlaces INTEGER,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (id_competition) REFERENCES competitions (id),
  FOREIGN KEY (id_club) REFERENCES clubs (id)
);
