DROP TABLE IF EXISTS clubs;
DROP TABLE IF EXISTS competitions;

CREATE TABLE clubs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email NVARCHAR(320),
  point INTEGER
);

CREATE TABLE competitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  date TIMESTAMP NOT NULL,
  numberOfPlaces INTEGER
);